name: Discord Notify

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Count changed files
        id: count
        run: |
          total=0

          for row in $(echo '${{ toJson(github.event.commits) }}' | jq -c '.[]'); do
            added=$(echo "$row" | jq '.added | length')
            modified=$(echo "$row" | jq '.modified | length')
            removed=$(echo "$row" | jq '.removed | length')

            total=$((total + added + modified + removed))
          done

          echo "total=$total" >> $GITHUB_OUTPUT

      - name: Send to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d "{
            \"content\": \"foram alterados ${{ steps.count.outputs.total }} arquivos neste push\"
          }" \
          ${{ secrets.DISCORD_WEBHOOK }}
