name: Discord Notify

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Count changed files
        id: count
        run: |
          count=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | wc -l)
          echo "total=$count" >> $GITHUB_OUTPUT

      - name: Send to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d "{
            \"content\": \"foram alterados ${{ steps.count.outputs.total }} arquivos neste push\"
          }" \
          ${{ secrets.DISCORD_WEBHOOK }}
