name: Discord Notify

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Count files
        id: count
        run: |
          count=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | wc -l)
          echo "total=$count" >> $GITHUB_OUTPUT

      - name: Get file list
        id: files
        run: |
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$files" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send embed to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d "{
            \"embeds\": [{
              \"title\": \"arquivos modificados\",
              \"description\": \"${{ steps.files.outputs.files }}\",
              \"color\": 16711680,
              \"thumbnail\": {
                \"url\": \"https://avatars.githubusercontent.com/u/203347761\"
              },
              \"fields\": [
                {
                  \"name\": \"quantidade\",
                  \"value\": \"${{ steps.count.outputs.total }} arquivos\"
                }
              ]
            }]
          }" \
          ${{ secrets.DISCORD_WEBHOOK }}
